### ISSUE TITLE
bug: incorrect ស៊ើប example

### ISSUE THREAD

**Issue by Nnyny** [clo-org-kh/pheasakhmer.com#5]
This example is incorrect but it shown as correct on Today keyboard. 

![image](https://github.com/user-attachments/assets/5bb09100-2bb4-49ce-86a0-827e4b2537bf)

**Comment by mcdurdin** [comment]
It's a spelling error rather than an encoding error as it is visibly wrong

**Comment by Nnyny** [comment]
Oh, I think I have to change the translation of "Text is encoded correctly" because the current translation is confusing.

**Comment by Nnyny** [comment]
Is it possible to change the green background color to something else (maybe yellow) to indicate this example as a special case?

**Comment by mcdurdin** [comment]
I'll have a think. I tried to clarify that this was a spelling error rather than an encoding error in the example documentation -- but not sure it was clear. What do you think? Could we improve the text?

**Comment by Nnyny** [comment]
The documentation did explain well about this case but do you need me to update any certain texts?

![image](https://github.com/user-attachments/assets/dd574acc-fbf2-40fc-b79d-e158afcc2532)

**Comment by mcdurdin** [comment]
Your explanation seems good to me but I need Makara to verify the translation

**Comment by mcdurdin** [comment]
OK I will go ahead and close this as Makara is separately verifying translations
