### ISSUE TITLE
bug: normalizer link doesn't work and isn't shown in About or Help either

### ISSUE THREAD

**Issue by mcdurdin** [clo-org-kh/pheasakhmer.com#9]

**Comment by Nnyny** [comment]
I accidently push [this](https://github.com/clo-org-kh/pheasakhmer.com/commit/6f748ef0433cd5d212ab258363bf2522ed2e7e0d) into main.

**Comment by mcdurdin** [comment]
> I accidentally push [this](https://github.com/clo-org-kh/pheasakhmer.com/commit/6f748ef0433cd5d212ab258363bf2522ed2e7e0d) into main.

Does that mean it all works now? If so, please go ahead and close this issue :)

**Comment by Nnyny** [comment]
It works when I tested it locally but I haven't seen it appear on the website yet.

**Comment by mcdurdin** [comment]
> It works when I tested it locally but I haven't seen it appear on the website yet.

It looks like it is there now :grin:
